---

# deploy one config
- name: Deploy one service
  include_tasks: loop_deploy_inner.yml
  vars:
    k8s_config1: "{{ k8s_config }}"
  when: k8s_config is defined

# deploy multiple config
- name: Deploy each service
  include_tasks: loop_deploy_inner.yml
  with_items: "{{ k8s_config_list }}"
  loop_control:
    loop_var: k8s_config1
  when: k8s_config_list is defined and ( k8s_config_name is not defined or k8s_config1.name == k8s_config_name ) and ( k8s_config1.on_k8s_namespace is not defined or k8s_config1.on_k8s_namespace == k8s_namespace )
